2023-12-01 22:21:21.982 | ERROR    | utils.loggings:exception:40 - (pymysql.err.DataError) (1264, "Out of range value for column 'UserID' at row 1")
[SQL: INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (%(UserID)s, %(UserName)s, %(RealName)s, %(Gender)s, %(IDCard)s, %(Email)s, %(Address)s, %(Account)s, %(Password)s)]
[parameters: {'UserID': 2023120122214816, 'UserName': None, 'RealName': None, 'Gender': None, 'IDCard': None, 'Email': None, 'Address': None, 'Account': '26', 'Password': '423'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Traceback (most recent call last):

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x000001BCFEE5BE20>
    │    └ <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x000001BCFF21DF90>
    └ <sqlalchemy.engine.base.Connection object at 0x000001BCFF9811E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'UserID': 2023120122214816, 'UserName': None, 'RealName': None, 'Gender': None, 'IDCard': None, 'Email': None, 'Address': No...
    │      │       └ 'INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
    │      └ <function Cursor.execute at 0x000001BCFF3F2DD0>
    └ <pymysql.cursors.Cursor object at 0x000001BCFF982890>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
             │    │      └ "INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
             │    └ <function Cursor._query at 0x000001BCFF3F3250>
             └ <pymysql.cursors.Cursor object at 0x000001BCFF982890>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
    │    │     └ "INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
    │    └ <function Connection.query at 0x000001BCFF40E290>
    └ <pymysql.connections.Connection object at 0x000001BCFF9818D0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    │    │                │    │                             └ False
    │    │                │    └ <function Connection._read_query_result at 0x000001BCFF40E8C0>
    │    │                └ <pymysql.connections.Connection object at 0x000001BCFF9818D0>
    │    └ 0
    └ <pymysql.connections.Connection object at 0x000001BCFF9818D0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
    │      └ <function MySQLResult.read at 0x000001BCFF40F0A0>
    └ <pymysql.connections.MySQLResult object at 0x000001BCFF982800>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
                   │    └ None
                   └ <pymysql.connections.MySQLResult object at 0x000001BCFF982800>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
    │      └ <function MysqlPacket.raise_for_error at 0x000001BCFF40CEE0>
    └ <pymysql.protocol.MysqlPacket object at 0x000001BCFF981F60>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
    │   │                     │    └ <member '_data' of 'MysqlPacket' objects>
    │   │                     └ <pymysql.protocol.MysqlPacket object at 0x000001BCFF981F60>
    │   └ <function raise_mysql_exception at 0x000001BCFF2D8D30>
    └ <module 'pymysql.err' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pymysql\\err....

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
          │          │      └ "Out of range value for column 'UserID' at row 1"
          │          └ 1264
          └ <class 'pymysql.err.DataError'>

pymysql.err.DataError: (1264, "Out of range value for column 'UserID' at row 1")


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001BCFB6FE710>
    └ <Thread(Thread-1 (serve_forever), started daemon 24812)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001BCFB6FE440>
    └ <Thread(Thread-1 (serve_forever), started daemon 24812)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (serve_forever), started daemon 24812)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (serve_forever), started daemon 24812)>
    │    └ <bound method BaseWSGIServer.serve_forever of <werkzeug.serving.BaseWSGIServer object at 0x000001BCFF9326E0>>
    └ <Thread(Thread-1 (serve_forever), started daemon 24812)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
                                        └ 0.5

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
    │    └ <function BaseServer._handle_request_noblock at 0x000001BCFB6FFE20>
    └ <werkzeug.serving.BaseWSGIServer object at 0x000001BCFF9326E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
    │    │               │        └ ('127.0.0.1', 52922)
    │    │               └ <socket.socket fd=340, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <function BaseServer.process_request at 0x000001BCFB704040>
    └ <werkzeug.serving.BaseWSGIServer object at 0x000001BCFF9326E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 52922)
    │    │              └ <socket.socket fd=340, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <function BaseServer.finish_request at 0x000001BCFB704160>
    └ <werkzeug.serving.BaseWSGIServer object at 0x000001BCFF9326E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.BaseWSGIServer object at 0x000001BCFF9326E0>
    │    │                   │        └ ('127.0.0.1', 52922)
    │    │                   └ <socket.socket fd=340, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.BaseWSGIServer object at 0x000001BCFF9326E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x000001BCFD47C790>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x000001BCFF980A30>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 390, in handle
    super().handle()

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 432, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x000001BCFD2C57E0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x000001BCFF980A30>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 420, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x000001BCFF980A30>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x000001BCFF930F40>
    │       │    └ <werkzeug.serving.BaseWSGIServer object at 0x000001BCFF9326E0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x000001BCFF980A30>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x000001BCFF98B370>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x000001BCFF8E3840>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x000001BCFF98AE60>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=340>, 'wsgi.errors': <_io.TextIOWr...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x000001BCFF930F40>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x000001BCFF98AE60>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=340>, 'wsgi.errors': <_io.TextIOWr...
           │    └ <function Flask.wsgi_app at 0x000001BCFDD27F40>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x000001BCFDD27490>
               └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x000001BCFDD27400>
         └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'users.register'
           │    │           │    │              └ <Rule '/api_1_0/users/register' (POST, OPTIONS) -> users.register>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x000001BCFF216F80>, 'apiversion.Apiversion': <function View.as_view...
           │    │           └ <Flask 'app'>
           │    └ <function Flask.ensure_sync at 0x000001BCFDD276D0>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\PycharmProjects\api_project\api\api_1_0\usersResource\urls.py", line 21, in register
    return UsersOtherResource.register()
           │                  └ <classmethod(<function UsersOtherResource.register at 0x000001BCFF906DD0>)>
           └ <class 'api_1_0.usersResource.usersOtherResource.UsersOtherResource'>

  File "C:\Users\Lenovo\PycharmProjects\api_project\api\api_1_0\usersResource\usersOtherResource.py", line 52, in register
    res = UsersService.register(**kwargs)
          │            │          └ {'account': '26', 'password': '423'}
          │            └ <classmethod(<function UsersService.register at 0x000001BCFF906050>)>
          └ <class 'service.usersService.UsersService'>

> File "C:\Users\Lenovo\PycharmProjects\api_project\api\service\usersService.py", line 66, in register
    db.session.commit()
    │  │       └ <function scoped_session.commit at 0x000001BCFF17F250>
    │  └ <sqlalchemy.orm.scoping.scoped_session object at 0x000001BCFDD63100>
    └ <SQLAlchemy mysql+pymysql://root:***@127.0.0.1:3306/project_1?charset=utf8>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\scoping.py", line 598, in commit
    return self._proxied.commit()
           │    └ <property object at 0x000001BCFF1A5170>
           └ <sqlalchemy.orm.scoping.scoped_session object at 0x000001BCFDD63100>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 1969, in commit
    trans.commit(_to_root=True)
    │     └ <function SessionTransaction.commit at 0x000001BCFF104B80>
    └ <sqlalchemy.orm.session.SessionTransaction object at 0x000001BCFF90B040>

  File "<string>", line 2, in commit

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                │  │      │      └ {'_to_root': True}
                │  │      └ ()
                │  └ <sqlalchemy.orm.session.SessionTransaction object at 0x000001BCFF90B040>
                └ <function SessionTransaction.commit at 0x000001BCFF104AF0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 1256, in commit
    self._prepare_impl()
    │    └ <function SessionTransaction._prepare_impl at 0x000001BCFF104A60>
    └ <sqlalchemy.orm.session.SessionTransaction object at 0x000001BCFF90B040>

  File "<string>", line 2, in _prepare_impl

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                │  │      │      └ {}
                │  │      └ ()
                │  └ <sqlalchemy.orm.session.SessionTransaction object at 0x000001BCFF90B040>
                └ <function SessionTransaction._prepare_impl at 0x000001BCFF104940>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 1231, in _prepare_impl
    self.session.flush()
    │    │       └ <function Session.flush at 0x000001BCFF107640>
    │    └ <sqlalchemy.orm.session.Session object at 0x000001BCFF9810C0>
    └ <sqlalchemy.orm.session.SessionTransaction object at 0x000001BCFF90B040>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 4312, in flush
    self._flush(objects)
    │    │      └ None
    │    └ <function Session._flush at 0x000001BCFF1077F0>
    └ <sqlalchemy.orm.session.Session object at 0x000001BCFF9810C0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 4447, in _flush
    with util.safe_reraise():
         │    └ <class 'sqlalchemy.util.langhelpers.safe_reraise'>
         └ <module 'sqlalchemy.util' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchem...

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
          │         │              └ <traceback object at 0x000001BCFFA6D040>
          │         └ <method 'with_traceback' of 'BaseException' objects>
          └ DataError('(pymysql.err.DataError) (1264, "Out of range value for column \'UserID\' at row 1")')

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 4408, in _flush
    flush_context.execute()
    │             └ <function UOWTransaction.execute at 0x000001BCFF0E9A20>
    └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x000001BCFF9828F0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    │   │       └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x000001BCFF9828F0>
    │   └ <function SaveUpdateAll.execute at 0x000001BCFF0EA320>
    └ SaveUpdateAll(Mapper[Users(users)])

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    │    │         │               └ <function save_obj at 0x000001BCFF0D88B0>
    │    │         └ <module 'sqlalchemy.orm.persistence' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages...
    │    └ <module 'sqlalchemy.util.preloaded' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\...
    └ <module 'sqlalchemy.util' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchem...

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    └ <function _emit_insert_statements at 0x000001BCFF0D92D0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\persistence.py", line 1043, in _emit_insert_statements
    result = connection.execute(
             │          └ <function Connection.execute at 0x000001BCFEDD89D0>
             └ <sqlalchemy.engine.base.Connection object at 0x000001BCFF9811E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           └ <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.dml.Insert object at 0x000001BCFF9835B0>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           │          └ <function Connection._execute_clauseelement at 0x000001BCFEDD8CA0>
           └ <sqlalchemy.engine.base.Connection object at 0x000001BCFF9811E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
          │    └ <function Connection._execute_context at 0x000001BCFEDD8E50>
          └ <sqlalchemy.engine.base.Connection object at 0x000001BCFF9811E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1848, in _execute_context
    return self._exec_single_context(
           │    └ <function Connection._exec_single_context at 0x000001BCFEDD8EE0>
           └ <sqlalchemy.engine.base.Connection object at 0x000001BCFF9811E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
    │    └ <function Connection._handle_dbapi_exception at 0x000001BCFEDD9120>
    └ <sqlalchemy.engine.base.Connection object at 0x000001BCFF9811E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
          │                    │              │                 └ DataError(1264, "Out of range value for column 'UserID' at row 1")
          │                    │              └ (<class 'pymysql.err.DataError'>, DataError(1264, "Out of range value for column 'UserID' at row 1"), <traceback object at 0x...
          │                    └ <method 'with_traceback' of 'BaseException' objects>
          └ DataError('(pymysql.err.DataError) (1264, "Out of range value for column \'UserID\' at row 1")')

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x000001BCFEE5BE20>
    │    └ <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x000001BCFF21DF90>
    └ <sqlalchemy.engine.base.Connection object at 0x000001BCFF9811E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'UserID': 2023120122214816, 'UserName': None, 'RealName': None, 'Gender': None, 'IDCard': None, 'Email': None, 'Address': No...
    │      │       └ 'INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
    │      └ <function Cursor.execute at 0x000001BCFF3F2DD0>
    └ <pymysql.cursors.Cursor object at 0x000001BCFF982890>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
             │    │      └ "INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
             │    └ <function Cursor._query at 0x000001BCFF3F3250>
             └ <pymysql.cursors.Cursor object at 0x000001BCFF982890>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
    │    │     └ "INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
    │    └ <function Connection.query at 0x000001BCFF40E290>
    └ <pymysql.connections.Connection object at 0x000001BCFF9818D0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    │    │                │    │                             └ False
    │    │                │    └ <function Connection._read_query_result at 0x000001BCFF40E8C0>
    │    │                └ <pymysql.connections.Connection object at 0x000001BCFF9818D0>
    │    └ 0
    └ <pymysql.connections.Connection object at 0x000001BCFF9818D0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
    │      └ <function MySQLResult.read at 0x000001BCFF40F0A0>
    └ <pymysql.connections.MySQLResult object at 0x000001BCFF982800>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
                   │    └ None
                   └ <pymysql.connections.MySQLResult object at 0x000001BCFF982800>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
    │      └ <function MysqlPacket.raise_for_error at 0x000001BCFF40CEE0>
    └ <pymysql.protocol.MysqlPacket object at 0x000001BCFF981F60>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
    │   │                     │    └ <member '_data' of 'MysqlPacket' objects>
    │   │                     └ <pymysql.protocol.MysqlPacket object at 0x000001BCFF981F60>
    │   └ <function raise_mysql_exception at 0x000001BCFF2D8D30>
    └ <module 'pymysql.err' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pymysql\\err....

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
          │          │      └ "Out of range value for column 'UserID' at row 1"
          │          └ 1264
          └ <class 'pymysql.err.DataError'>

sqlalchemy.exc.DataError: (pymysql.err.DataError) (1264, "Out of range value for column 'UserID' at row 1")
[SQL: INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (%(UserID)s, %(UserName)s, %(RealName)s, %(Gender)s, %(IDCard)s, %(Email)s, %(Address)s, %(Account)s, %(Password)s)]
[parameters: {'UserID': 2023120122214816, 'UserName': None, 'RealName': None, 'Gender': None, 'IDCard': None, 'Email': None, 'Address': None, 'Account': '26', 'Password': '423'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2023-12-01 22:22:21.388 | ERROR    | utils.loggings:exception:40 - (pymysql.err.DataError) (1264, "Out of range value for column 'UserID' at row 1")
[SQL: INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (%(UserID)s, %(UserName)s, %(RealName)s, %(Gender)s, %(IDCard)s, %(Email)s, %(Address)s, %(Account)s, %(Password)s)]
[parameters: {'UserID': 2023120122215726, 'UserName': None, 'RealName': None, 'Gender': None, 'IDCard': None, 'Email': None, 'Address': None, 'Account': '26', 'Password': '423'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Traceback (most recent call last):

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x000001B6C37645E0>
    │    └ <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x000001B6C3B15720>
    └ <sqlalchemy.engine.base.Connection object at 0x000001B6C5390CA0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'UserID': 2023120122215726, 'UserName': None, 'RealName': None, 'Gender': None, 'IDCard': None, 'Email': None, 'Address': No...
    │      │       └ 'INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
    │      └ <function Cursor.execute at 0x000001B6C4C8AEF0>
    └ <pymysql.cursors.Cursor object at 0x000001B6C5393BB0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
             │    │      └ "INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
             │    └ <function Cursor._query at 0x000001B6C4C8B370>
             └ <pymysql.cursors.Cursor object at 0x000001B6C5393BB0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
    │    │     └ "INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
    │    └ <function Connection.query at 0x000001B6C4CDA680>
    └ <pymysql.connections.Connection object at 0x000001B6C5390370>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    │    │                │    │                             └ False
    │    │                │    └ <function Connection._read_query_result at 0x000001B6C4CDACB0>
    │    │                └ <pymysql.connections.Connection object at 0x000001B6C5390370>
    │    └ 0
    └ <pymysql.connections.Connection object at 0x000001B6C5390370>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
    │      └ <function MySQLResult.read at 0x000001B6C4CDB490>
    └ <pymysql.connections.MySQLResult object at 0x000001B6C5393850>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
                   │    └ None
                   └ <pymysql.connections.MySQLResult object at 0x000001B6C5393850>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
    │      └ <function MysqlPacket.raise_for_error at 0x000001B6C4CD9240>
    └ <pymysql.protocol.MysqlPacket object at 0x000001B6C5390F10>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
    │   │                     │    └ <member '_data' of 'MysqlPacket' objects>
    │   │                     └ <pymysql.protocol.MysqlPacket object at 0x000001B6C5390F10>
    │   └ <function raise_mysql_exception at 0x000001B6C3BE0670>
    └ <module 'pymysql.err' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pymysql\\err....

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
          │          │      └ "Out of range value for column 'UserID' at row 1"
          │          └ 1264
          └ <class 'pymysql.err.DataError'>

pymysql.err.DataError: (1264, "Out of range value for column 'UserID' at row 1")


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "E:\pycharm\PyCharm2023.2.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 805, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x000001B6C5283970>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x000001B6C5283970>
          │    └ <bound method Thread._bootstrap of <Thread(Thread-5 (serve_forever), started daemon 27396)>>
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x000001B6C5283970>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001B6BFCDEE60>
    └ <Thread(Thread-5 (serve_forever), started daemon 27396)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001B6BFCDEB90>
    └ <Thread(Thread-5 (serve_forever), started daemon 27396)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5 (serve_forever), started daemon 27396)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-5 (serve_forever), started daemon 27396)>
    │    └ <bound method BaseWSGIServer.serve_forever of <werkzeug.serving.BaseWSGIServer object at 0x000001B6C2A61C30>>
    └ <Thread(Thread-5 (serve_forever), started daemon 27396)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
                                        └ 0.5

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
    │    └ <function BaseServer._handle_request_noblock at 0x000001B6C0397E20>
    └ <werkzeug.serving.BaseWSGIServer object at 0x000001B6C2A61C30>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
    │    │               │        └ ('127.0.0.1', 52939)
    │    │               └ <socket.socket fd=832, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <function BaseServer.process_request at 0x000001B6C1BE8040>
    └ <werkzeug.serving.BaseWSGIServer object at 0x000001B6C2A61C30>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 52939)
    │    │              └ <socket.socket fd=832, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <function BaseServer.finish_request at 0x000001B6C1BE8160>
    └ <werkzeug.serving.BaseWSGIServer object at 0x000001B6C2A61C30>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.BaseWSGIServer object at 0x000001B6C2A61C30>
    │    │                   │        └ ('127.0.0.1', 52939)
    │    │                   └ <socket.socket fd=832, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.BaseWSGIServer object at 0x000001B6C2A61C30>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x000001B6C2BE1AB0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x000001B6C5283D00>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 390, in handle
    super().handle()

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 432, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x000001B6C1BE9870>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x000001B6C5283D00>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 420, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x000001B6C5283D00>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x000001B6C5256B30>
    │       │    └ <werkzeug.serving.BaseWSGIServer object at 0x000001B6C2A61C30>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x000001B6C5283D00>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x000001B6C5352680>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x000001B6C5203760>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x000001B6C5352320>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=832>, 'wsgi.errors': <_io.TextIOWr...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x000001B6C5256B30>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x000001B6C5352320>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=832>, 'wsgi.errors': <_io.TextIOWr...
           │    └ <function Flask.wsgi_app at 0x000001B6C2F3BC70>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x000001B6C2F3B1C0>
               └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x000001B6C2F3B130>
         └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'users.register'
           │    │           │    │              └ <Rule '/api_1_0/users/register' (OPTIONS, POST) -> users.register>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x000001B6C3B227A0>, 'apiversion.Apiversion': <function View.as_view...
           │    │           └ <Flask 'app'>
           │    └ <function Flask.ensure_sync at 0x000001B6C2F3B400>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\PycharmProjects\api_project\api\api_1_0\usersResource\urls.py", line 21, in register
    return UsersOtherResource.register()
           │                  └ <classmethod(<function UsersOtherResource.register at 0x000001B6C523BE20>)>
           └ <class 'api_1_0.usersResource.usersOtherResource.UsersOtherResource'>

  File "C:\Users\Lenovo\PycharmProjects\api_project\api\api_1_0\usersResource\usersOtherResource.py", line 52, in register
    res = UsersService.register(**kwargs)
          │            │          └ {'account': '26', 'password': '423'}
          │            └ <classmethod(<function UsersService.register at 0x000001B6C523B0A0>)>
          └ <class 'service.usersService.UsersService'>

> File "C:\Users\Lenovo\PycharmProjects\api_project\api\service\usersService.py", line 66, in register
    db.session.commit()
    │  │       └ <function scoped_session.commit at 0x000001B6C3A83AC0>
    │  └ <sqlalchemy.orm.scoping.scoped_session object at 0x000001B6C30E0190>
    └ <SQLAlchemy mysql+pymysql://root:***@127.0.0.1:3306/project_1?charset=utf8>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\scoping.py", line 598, in commit
    return self._proxied.commit()
           │    └ <property object at 0x000001B6C3A91E90>
           └ <sqlalchemy.orm.scoping.scoped_session object at 0x000001B6C30E0190>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 1969, in commit
    trans.commit(_to_root=True)
    │     └ <function SessionTransaction.commit at 0x000001B6C3A053F0>
    └ <sqlalchemy.orm.session.SessionTransaction object at 0x000001B6C5287680>

  File "<string>", line 2, in commit

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                │  │      │      └ {'_to_root': True}
                │  │      └ ()
                │  └ <sqlalchemy.orm.session.SessionTransaction object at 0x000001B6C5287680>
                └ <function SessionTransaction.commit at 0x000001B6C3A05360>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 1256, in commit
    self._prepare_impl()
    │    └ <function SessionTransaction._prepare_impl at 0x000001B6C3A052D0>
    └ <sqlalchemy.orm.session.SessionTransaction object at 0x000001B6C5287680>

  File "<string>", line 2, in _prepare_impl

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                │  │      │      └ {}
                │  │      └ ()
                │  └ <sqlalchemy.orm.session.SessionTransaction object at 0x000001B6C5287680>
                └ <function SessionTransaction._prepare_impl at 0x000001B6C3A051B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 1231, in _prepare_impl
    self.session.flush()
    │    │       └ <function Session.flush at 0x000001B6C3A07EB0>
    │    └ <sqlalchemy.orm.session.Session object at 0x000001B6C5390790>
    └ <sqlalchemy.orm.session.SessionTransaction object at 0x000001B6C5287680>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 4312, in flush
    self._flush(objects)
    │    │      └ None
    │    └ <function Session._flush at 0x000001B6C3A0C0D0>
    └ <sqlalchemy.orm.session.Session object at 0x000001B6C5390790>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 4447, in _flush
    with util.safe_reraise():
         │    └ <class 'sqlalchemy.util.langhelpers.safe_reraise'>
         └ <module 'sqlalchemy.util' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchem...

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
          │         │              └ <traceback object at 0x000001B6C545C0C0>
          │         └ <method 'with_traceback' of 'BaseException' objects>
          └ DataError('(pymysql.err.DataError) (1264, "Out of range value for column \'UserID\' at row 1")')

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 4408, in _flush
    flush_context.execute()
    │             └ <function UOWTransaction.execute at 0x000001B6C39F2290>
    └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x000001B6C52839A0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    │   │       └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x000001B6C52839A0>
    │   └ <function SaveUpdateAll.execute at 0x000001B6C39F2B90>
    └ SaveUpdateAll(Mapper[Users(users)])

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    │    │         │               └ <function save_obj at 0x000001B6C39DD120>
    │    │         └ <module 'sqlalchemy.orm.persistence' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages...
    │    └ <module 'sqlalchemy.util.preloaded' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\...
    └ <module 'sqlalchemy.util' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchem...

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    └ <function _emit_insert_statements at 0x000001B6C39DDB40>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\persistence.py", line 1043, in _emit_insert_statements
    result = connection.execute(
             │          └ <function Connection.execute at 0x000001B6C36C4EE0>
             └ <sqlalchemy.engine.base.Connection object at 0x000001B6C5390CA0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           └ <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.dml.Insert object at 0x000001B6C53930A0>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           │          └ <function Connection._execute_clauseelement at 0x000001B6C36C51B0>
           └ <sqlalchemy.engine.base.Connection object at 0x000001B6C5390CA0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
          │    └ <function Connection._execute_context at 0x000001B6C36C5360>
          └ <sqlalchemy.engine.base.Connection object at 0x000001B6C5390CA0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1848, in _execute_context
    return self._exec_single_context(
           │    └ <function Connection._exec_single_context at 0x000001B6C36C53F0>
           └ <sqlalchemy.engine.base.Connection object at 0x000001B6C5390CA0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
    │    └ <function Connection._handle_dbapi_exception at 0x000001B6C36C5630>
    └ <sqlalchemy.engine.base.Connection object at 0x000001B6C5390CA0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
          │                    │              │                 └ DataError(1264, "Out of range value for column 'UserID' at row 1")
          │                    │              └ (<class 'pymysql.err.DataError'>, DataError(1264, "Out of range value for column 'UserID' at row 1"), <traceback object at 0x...
          │                    └ <method 'with_traceback' of 'BaseException' objects>
          └ DataError('(pymysql.err.DataError) (1264, "Out of range value for column \'UserID\' at row 1")')

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x000001B6C37645E0>
    │    └ <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x000001B6C3B15720>
    └ <sqlalchemy.engine.base.Connection object at 0x000001B6C5390CA0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'UserID': 2023120122215726, 'UserName': None, 'RealName': None, 'Gender': None, 'IDCard': None, 'Email': None, 'Address': No...
    │      │       └ 'INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
    │      └ <function Cursor.execute at 0x000001B6C4C8AEF0>
    └ <pymysql.cursors.Cursor object at 0x000001B6C5393BB0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
             │    │      └ "INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
             │    └ <function Cursor._query at 0x000001B6C4C8B370>
             └ <pymysql.cursors.Cursor object at 0x000001B6C5393BB0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
    │    │     └ "INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
    │    └ <function Connection.query at 0x000001B6C4CDA680>
    └ <pymysql.connections.Connection object at 0x000001B6C5390370>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    │    │                │    │                             └ False
    │    │                │    └ <function Connection._read_query_result at 0x000001B6C4CDACB0>
    │    │                └ <pymysql.connections.Connection object at 0x000001B6C5390370>
    │    └ 0
    └ <pymysql.connections.Connection object at 0x000001B6C5390370>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
    │      └ <function MySQLResult.read at 0x000001B6C4CDB490>
    └ <pymysql.connections.MySQLResult object at 0x000001B6C5393850>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
                   │    └ None
                   └ <pymysql.connections.MySQLResult object at 0x000001B6C5393850>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
    │      └ <function MysqlPacket.raise_for_error at 0x000001B6C4CD9240>
    └ <pymysql.protocol.MysqlPacket object at 0x000001B6C5390F10>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
    │   │                     │    └ <member '_data' of 'MysqlPacket' objects>
    │   │                     └ <pymysql.protocol.MysqlPacket object at 0x000001B6C5390F10>
    │   └ <function raise_mysql_exception at 0x000001B6C3BE0670>
    └ <module 'pymysql.err' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pymysql\\err....

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
          │          │      └ "Out of range value for column 'UserID' at row 1"
          │          └ 1264
          └ <class 'pymysql.err.DataError'>

sqlalchemy.exc.DataError: (pymysql.err.DataError) (1264, "Out of range value for column 'UserID' at row 1")
[SQL: INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (%(UserID)s, %(UserName)s, %(RealName)s, %(Gender)s, %(IDCard)s, %(Email)s, %(Address)s, %(Account)s, %(Password)s)]
[parameters: {'UserID': 2023120122215726, 'UserName': None, 'RealName': None, 'Gender': None, 'IDCard': None, 'Email': None, 'Address': None, 'Account': '26', 'Password': '423'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2023-12-01 22:22:50.957 | ERROR    | utils.loggings:exception:40 - 'int' object is not subscriptable
Traceback (most recent call last):

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000232C597E710>
    └ <Thread(Thread-1 (serve_forever), started daemon 25652)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x00000232C597E440>
    └ <Thread(Thread-1 (serve_forever), started daemon 25652)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (serve_forever), started daemon 25652)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (serve_forever), started daemon 25652)>
    │    └ <bound method BaseWSGIServer.serve_forever of <werkzeug.serving.BaseWSGIServer object at 0x00000232C9BA26E0>>
    └ <Thread(Thread-1 (serve_forever), started daemon 25652)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
                                        └ 0.5

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
    │    └ <function BaseServer._handle_request_noblock at 0x00000232C597FE20>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000232C9BA26E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
    │    │               │        └ ('127.0.0.1', 52964)
    │    │               └ <socket.socket fd=896, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <function BaseServer.process_request at 0x00000232C5984040>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000232C9BA26E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 52964)
    │    │              └ <socket.socket fd=896, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <function BaseServer.finish_request at 0x00000232C5984160>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000232C9BA26E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.BaseWSGIServer object at 0x00000232C9BA26E0>
    │    │                   │        └ ('127.0.0.1', 52964)
    │    │                   └ <socket.socket fd=896, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000232C9BA26E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x00000232C76F0790>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x00000232C9BEC9D0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 390, in handle
    super().handle()

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 432, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x00000232C75357E0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x00000232C9BEC9D0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 420, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x00000232C9BEC9D0>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x00000232C9BA0F40>
    │       │    └ <werkzeug.serving.BaseWSGIServer object at 0x00000232C9BA26E0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x00000232C9BEC9D0>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x00000232C9BF7B50>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x00000232C9B4F7D0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x00000232C9BF75B0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=896>, 'wsgi.errors': <_io.TextIOWr...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x00000232C9BA0F40>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x00000232C9BF75B0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=896>, 'wsgi.errors': <_io.TextIOWr...
           │    └ <function Flask.wsgi_app at 0x00000232C7F97F40>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x00000232C7F97490>
               └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x00000232C7F97400>
         └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'users.register'
           │    │           │    │              └ <Rule '/api_1_0/users/register' (OPTIONS, POST) -> users.register>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x00000232C949AF80>, 'apiversion.Apiversion': <function View.as_view...
           │    │           └ <Flask 'app'>
           │    └ <function Flask.ensure_sync at 0x00000232C7F976D0>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\PycharmProjects\api_project\api\api_1_0\usersResource\urls.py", line 21, in register
    return UsersOtherResource.register()
           │                  └ <classmethod(<function UsersOtherResource.register at 0x00000232C9B76E60>)>
           └ <class 'api_1_0.usersResource.usersOtherResource.UsersOtherResource'>

  File "C:\Users\Lenovo\PycharmProjects\api_project\api\api_1_0\usersResource\usersOtherResource.py", line 52, in register
    res = UsersService.register(**kwargs)
          │            │          └ {'account': '26', 'password': '423'}
          │            └ <classmethod(<function UsersService.register at 0x00000232C9B760E0>)>
          └ <class 'service.usersService.UsersService'>

> File "C:\Users\Lenovo\PycharmProjects\api_project\api\service\usersService.py", line 63, in register
    new_user = cls(UserID=id[0:4],Account=account, Password=password)
               │          │               │                 └ '423'
               │          │               └ '26'
               │          └ 2023120122228045
               └ <class 'service.usersService.UsersService'>

TypeError: 'int' object is not subscriptable
2023-12-01 22:25:35.306 | ERROR    | utils.loggings:exception:40 - 'int' object is not subscriptable
Traceback (most recent call last):

  File "E:\pycharm\PyCharm2023.2.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 805, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x00000249168E39A0>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x00000249168E39A0>
          │    └ <bound method Thread._bootstrap of <Thread(Thread-5 (serve_forever), started daemon 14464)>>
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x00000249168E39A0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002491131EE60>
    └ <Thread(Thread-5 (serve_forever), started daemon 14464)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002491131EB90>
    └ <Thread(Thread-5 (serve_forever), started daemon 14464)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5 (serve_forever), started daemon 14464)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-5 (serve_forever), started daemon 14464)>
    │    └ <bound method BaseWSGIServer.serve_forever of <werkzeug.serving.BaseWSGIServer object at 0x00000249140C1C60>>
    └ <Thread(Thread-5 (serve_forever), started daemon 14464)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
                                        └ 0.5

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
    │    └ <function BaseServer._handle_request_noblock at 0x00000249119F7E20>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000249140C1C60>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
    │    │               │        └ ('127.0.0.1', 54212)
    │    │               └ <socket.socket fd=1116, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <function BaseServer.process_request at 0x0000024913248040>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000249140C1C60>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 54212)
    │    │              └ <socket.socket fd=1116, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <function BaseServer.finish_request at 0x0000024913248160>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000249140C1C60>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.BaseWSGIServer object at 0x00000249140C1C60>
    │    │                   │        └ ('127.0.0.1', 54212)
    │    │                   └ <socket.socket fd=1116, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000249140C1C60>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x0000024914241AB0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x00000249168B7430>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 390, in handle
    super().handle()

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 432, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x0000024913249870>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x00000249168B7430>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 420, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x00000249168B7430>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x00000249168B6B60>
    │       │    └ <werkzeug.serving.BaseWSGIServer object at 0x00000249140C1C60>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x00000249168B7430>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x00000249169B6710>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x0000024916862FF0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x00000249169B64D0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=1116>, 'wsgi.errors': <_io.TextIOW...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x00000249168B6B60>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x00000249169B64D0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=1116>, 'wsgi.errors': <_io.TextIOW...
           │    └ <function Flask.wsgi_app at 0x000002491459BC70>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x000002491459B1C0>
               └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x000002491459B130>
         └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'users.register'
           │    │           │    │              └ <Rule '/api_1_0/users/register' (POST, OPTIONS) -> users.register>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x00000249151827A0>, 'apiversion.Apiversion': <function View.as_view...
           │    │           └ <Flask 'app'>
           │    └ <function Flask.ensure_sync at 0x000002491459B400>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\PycharmProjects\api_project\api\api_1_0\usersResource\urls.py", line 21, in register
    return UsersOtherResource.register()
           │                  └ <classmethod(<function UsersOtherResource.register at 0x000002491689BEB0>)>
           └ <class 'api_1_0.usersResource.usersOtherResource.UsersOtherResource'>

  File "C:\Users\Lenovo\PycharmProjects\api_project\api\api_1_0\usersResource\usersOtherResource.py", line 52, in register
    res = UsersService.register(**kwargs)
          │            │          └ {'account': '28', 'password': '423'}
          │            └ <classmethod(<function UsersService.register at 0x000002491689B130>)>
          └ <class 'service.usersService.UsersService'>

> File "C:\Users\Lenovo\PycharmProjects\api_project\api\service\usersService.py", line 62, in register
    id=int(GenerateID.create_random_id())[0:4]
           │          └ <staticmethod(<function GenerateID.create_random_id at 0x000002491689B010>)>
           └ <class 'utils.generate_id.GenerateID'>

TypeError: 'int' object is not subscriptable
2023-12-01 22:26:12.704 | ERROR    | utils.loggings:exception:40 - 'int' object is not subscriptable
Traceback (most recent call last):

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000019A80CAE710>
    └ <Thread(Thread-1 (serve_forever), started daemon 26192)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000019A80CAE440>
    └ <Thread(Thread-1 (serve_forever), started daemon 26192)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (serve_forever), started daemon 26192)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (serve_forever), started daemon 26192)>
    │    └ <bound method BaseWSGIServer.serve_forever of <werkzeug.serving.BaseWSGIServer object at 0x0000019A84ED26E0>>
    └ <Thread(Thread-1 (serve_forever), started daemon 26192)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
                                        └ 0.5

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
    │    └ <function BaseServer._handle_request_noblock at 0x0000019A80CAFE20>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000019A84ED26E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
    │    │               │        └ ('127.0.0.1', 54226)
    │    │               └ <socket.socket fd=1072, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <function BaseServer.process_request at 0x0000019A80CB4040>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000019A84ED26E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 54226)
    │    │              └ <socket.socket fd=1072, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <function BaseServer.finish_request at 0x0000019A80CB4160>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000019A84ED26E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.BaseWSGIServer object at 0x0000019A84ED26E0>
    │    │                   │        └ ('127.0.0.1', 54226)
    │    │                   └ <socket.socket fd=1072, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000019A84ED26E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x0000019A82A20790>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x0000019A84F20AF0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 390, in handle
    super().handle()

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 432, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x0000019A828657E0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x0000019A84F20AF0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 420, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x0000019A84F20AF0>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x0000019A84ED0F40>
    │       │    └ <werkzeug.serving.BaseWSGIServer object at 0x0000019A84ED26E0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x0000019A84F20AF0>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x0000019A84F27B50>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x0000019A84E7B760>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x0000019A84F26830>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=1072>, 'wsgi.errors': <_io.TextIOW...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x0000019A84ED0F40>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x0000019A84F26830>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=1072>, 'wsgi.errors': <_io.TextIOW...
           │    └ <function Flask.wsgi_app at 0x0000019A832C7F40>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x0000019A832C7490>
               └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x0000019A832C7400>
         └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'users.register'
           │    │           │    │              └ <Rule '/api_1_0/users/register' (POST, OPTIONS) -> users.register>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x0000019A847CAF80>, 'apiversion.Apiversion': <function View.as_view...
           │    │           └ <Flask 'app'>
           │    └ <function Flask.ensure_sync at 0x0000019A832C76D0>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\PycharmProjects\api_project\api\api_1_0\usersResource\urls.py", line 21, in register
    return UsersOtherResource.register()
           │                  └ <classmethod(<function UsersOtherResource.register at 0x0000019A84EA6E60>)>
           └ <class 'api_1_0.usersResource.usersOtherResource.UsersOtherResource'>

  File "C:\Users\Lenovo\PycharmProjects\api_project\api\api_1_0\usersResource\usersOtherResource.py", line 52, in register
    res = UsersService.register(**kwargs)
          │            │          └ {'account': '28', 'password': '423'}
          │            └ <classmethod(<function UsersService.register at 0x0000019A84EA60E0>)>
          └ <class 'service.usersService.UsersService'>

> File "C:\Users\Lenovo\PycharmProjects\api_project\api\service\usersService.py", line 62, in register
    id=int(GenerateID.create_random_id())[0:4]
           │          └ <staticmethod(<function GenerateID.create_random_id at 0x0000019A84EA5FC0>)>
           └ <class 'utils.generate_id.GenerateID'>

TypeError: 'int' object is not subscriptable
